[package]
name = "aoc_2015"
description.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
aoc_utils.workspace = true
regex = "1.11.1"
fancy-regex = "0.14.0"
